---
version: "3"
services:
  homer:
    image: b4bz/homer
    volumes:
      - homer-data:/www/assets
    user: 1000:1000 # default
    restart: always
    depends_on:
      - homer-tailscale
    network_mode: service:homer-tailscale
    
  homer-tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:latest
    restart: always
    environment:
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: home
      TAILSCALE_SERVE_PORT: 8080

volumes:
  homer-data:
    driver: local
