---
version: "3"
services:
  homer:
    image: b4bz/homer:latest
    volumes:
      - homer-data:/www/assets
    user: 1000:1000 # default
    restart: always
    depends_on:
      - homer-tailscale
    network_mode: service:homer-tailscale
    
  homer-tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:v1.46.1
    restart: always
    environment:
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: homer
      TAILSCALE_SERVE_PORT: 8080
    volumes:
      - tailscale:/var/lib/tailscale_state

volumes:
  homer-data:
  tailscale:
