---
version: "3"
services:
  homer:
    image: b4bz/homer:latest
    volumes:
      - homer-data:/www/assets
    user: 1000:1000 # default
    restart: always
    depends_on:
      - homer-tailscale
    network_mode: service:homer-tailscale
    
  homer-tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:v1.48.2
    restart: always
    environment:
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: home
      TAILSCALE_SERVE_PORT: 8080
      TAILSCALE_SSH: true
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_MODE: https
      TAILSCALE_SERVE_SOURCE_MODE: http
    volumes:
      - tailscale-state:/var/lib/tailscale

volumes:
  homer-data:
  tailscale-state:
