version: '3.3'
services:
  busylight-docker:
    devices:
      - /dev/bus
    image: ghcr.io/elliotmatson/busylight-docker:v0.26.1
    restart: always
    depends_on:
      - tailscale
    network_mode: service:tailscale
    deploy:
      resources:
        limits:
          cpus: "0.15"
    healthcheck:
      test: ["CMD", "curl", "busylight:8000/"]
      interval: 30s
      retries: 3
  tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:1.64.2
    restart: always
    environment:
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: busylight
      TAILSCALE_SERVE_PORT: 8000
      TAILSCALE_SSH: true
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_SOURCE_MODE: http
    volumes:
      - tailscale-state:/var/lib/tailscale

volumes:
  tailscale-state: