version: '3.3'
services:
    tsrecorder:
        environment:
            - TS_AUTHKEY=$TS_AUTHKEY
        volumes:
            - tsrecorder:/data
        image: tailscale/tsrecorder:stable
        restart: unless-stopped
        command:
          - --dst=/data/recordings
          - --statedir=/data/state 
          - --hostname=session-recorder
          - --ui

volumes:
    tsrecorder: