---
version: "3.3"
services:
  tsrecorder:
    environment:
      - TS_AUTHKEY=$TS_AUTHKEY
    volumes:
      - tsrecorder:/data
    image: tailscale/tsrecorder:v1.84.0
    restart: on-failure
    command:
      - /tsrecorder
      - --dst=/data/recordings
      - --statedir=/data/state
      - --hostname=session-recorder
      - --ui

volumes:
  tsrecorder:
