---
version: "3"
services:
  kuma:
    image: louislam/uptime-kuma:2.0.0-beta.1
    environment:
      - TZ=America/Chicago
    volumes:
      - kuma-db:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - kuma-tailscale
    network_mode: service:kuma-tailscale

  kuma-tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:1.78.3
    restart: always
    environment:
      TAILSCALE_SSH: true
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_SOURCE_MODE: http
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: status
      TAILSCALE_FUNNEL: true
      TAILSCALE_SERVE_PORT: 3001
    volumes:
      - tailscale-state:/var/lib/tailscale

  uptime-buddy-api:
    image: schech1/uptime-buddy-api:latest
    restart: always
    #ports:
    #  - "5005:5005" # If you change the port, also change the PORT Env var
    environment:
      - UPTIME_KUMA_URL=https://status.tail5c441.ts.net/ # e.g. http://192.168.1.34:3002/
      - EXTERNAL_URL=https://status.tail5c441.ts.net # Optional: e.g. https://uptime.domain.com Use this if you want to use the Qr code feature
      - USERNAME=${UPTIME_BUDDY_USER:?err} #Optional: remove line if auth is disabled in Uptime Kuma
      - PASSWORD=${UPTIME_BUDDY_PASSWORD:?err} #Optional: remove line if auth is disabled in Uptime Kuma
      - TOKEN=${UPTIME_BUDDY_TOKEN:?err}
      - MFA=true #Is 2FA enabled in Uptime Kuma?
    network_mode: service:buddy-tailscale
    
  buddy-tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:1.78.3
    restart: always
    environment:
      TAILSCALE_SSH: true
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_SOURCE_MODE: http
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: status-api
      TAILSCALE_FUNNEL: true
      TAILSCALE_SERVE_PORT: 5005
    volumes:
      - buddy-tailscale-state:/var/lib/tailscale

#  api:
#    image: medaziz11/uptimekuma_restapi:latest
#    volumes:
#      - api-db:/db
#    restart: always
#    environment:
#      - ${KUMA_USERNAME:?err}
#      - ${KUMA_PASSWORD:?err}
#      - ${ADMIN_PASSWORD:?err}
#      - ${KUMA_SERVER:?err}
#      - ${ACCESS_TOKEN_EXPIRE:?err}
#      - ${SECRET_KEY:?err}
#    depends_on:
#      - kuma
#      - api-tailscale
#    network_mode: service:api-tailscale
#  api-tailscale:
#    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:v0.0.13
#    restart: on-failure
#    environment:
#      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
#      TAILSCALE_HOSTNAME: kumaapi
#      TAILSCALE_SERVE_PORT: 8000

volumes:
  kuma-db:
  tailscale-state:
  buddy-tailscale-state:
#  api-db:

