---
version: "3"
services:
  kuma:
    image: louislam/uptime-kuma:2.0.0-beta.2
    environment:
      - TZ=America/Chicago
    volumes:
      - kuma-db:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: on-failure
    depends_on:
      - kuma-tailscale
    network_mode: service:kuma-tailscale

  kuma-tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:1.80.3
    restart: always
    environment:
      TAILSCALE_SSH: true
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_SOURCE_MODE: http
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: status
      TAILSCALE_FUNNEL: true
      TAILSCALE_SERVE_PORT: 3001
    volumes:
      - tailscale-state:/var/lib/tailscale
#  api:
#    image: medaziz11/uptimekuma_restapi:latest
#    volumes:
#      - api-db:/db
#    restart: always
#    environment:
#      - ${KUMA_USERNAME:?err}
#      - ${KUMA_PASSWORD:?err}
#      - ${ADMIN_PASSWORD:?err}
#      - ${KUMA_SERVER:?err}
#      - ${ACCESS_TOKEN_EXPIRE:?err}
#      - ${SECRET_KEY:?err}
#    depends_on:
#      - kuma
#      - api-tailscale
#    network_mode: service:api-tailscale
#  api-tailscale:
#    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:v0.0.13
#    restart: on-failure
#    environment:
#      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
#      TAILSCALE_HOSTNAME: kumaapi
#      TAILSCALE_SERVE_PORT: 8000

volumes:
  kuma-db:
  tailscale-state:
  buddy-tailscale-state:
#  api-db:

