---
version: "3"
services:
  kuma:
    image: louislam/uptime-kuma:1.22
    environment:
      - TZ=America/Chicago
    volumes:
      - /home/elliotmatson/containers/uptime-kuma/data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock:ro
    restart: always
    depends_on:
      - kuma-tailscale
    network_mode: service:kuma-tailscale
  kuma-tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:v0.0.13
    restart: always
    environment:
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: status
      TAILSCALE_SERVE_PORT: 3001

volumes:
  kuma-db:
  api-db:
