---
version: "3"

services:
  semaphore:
    image: semaphoreui/semaphore:v2.8.94
    env_file:
      - ../stack.env
    volumes:
      - config:/etc/semaphore # config.json location
      - db:/var/lib/semaphore # database.boltdb location (Not required if using mysql or postgres)
    restart: always
    depends_on:
      - tailscale
    network_mode: service:tailscale
  tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:v1.48.1
    restart: always
    environment:
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: semaphore
      TAILSCALE_SERVE_PORT: 3000
      TZ: America/Chicago
      
volumes:
  db:
  config: