---
version: "3"

services:
  semaphore:
    image: ghcr.io/elliotmatson/ansible-semaphore-ts:v2.9.75
    env_file:
      - ../stack.env
    volumes:
      - config:/etc/semaphore # config.json location
      - db:/var/lib/semaphore # database.boltdb location
      - tailscale-state:/var/lib/tailscale
    restart: on-failure

volumes:
  db:
  config:
  tailscale-state:
