---
version: "3"

services:
  semaphore:
    image: ghcr.io/elliotmatson/ansible-semaphore-ts:v2.9.64
    env_file:
      - ../stack.env
    volumes:
      - config:/etc/semaphore # config.json location
      - db:/var/lib/semaphore # database.boltdb location (Not required if using mysql or postgres)
      - tailscale-state:/var/lib/tailscale
    restart: always
      
volumes:
  db:
  config:
  tailscale-state:
