version: '3'

services:
  influxdb:
    image: influxdb:2.7.6
    volumes:
      - influxdb-data:/var/lib/influxdb2:rw
    restart: unless-stopped
    depends_on:
      - tailscale
    network_mode: service:tailscale
    healthcheck:
      test: ["CMD", "curl", "influxdb:8086/api/v2/ping"]
      interval: 30s
      retries: 3
    
  tailscale:
    image: ghcr.io/elliotmatson/tailscale-sidecar-proxy:1.64.1
    restart: always
    environment:
      TAILSCALE_AUTH_KEY: ${TS_AUTH_KEY:?err}
      TAILSCALE_HOSTNAME: influxdb
      TAILSCALE_SERVE_PORT: 8086
      TAILSCALE_SSH: false
      TAILSCALE_FUNNEL: true
      TAILSCALE_STATE_DIR: /var/lib/tailscale
      TAILSCALE_SERVE_SOURCE_MODE: http
    volumes:
      - tailscale-state:/var/lib/tailscale

volumes:
  influxdb-data:
  tailscale-state: