---
- name: clean docker
  hosts: docker
  tasks:
    - name: Install python3-docker
      apt:
        name: python3-docker
        state: present
        update_cache: yes
    - name: prune non-dangling images
      community.docker.docker_prune:
        containers: false
        images: true
        images_filters:
          dangling: false
        networks: false
        volumes: false
        builder_cache: false