---
- hosts: debian_based

  become: yes
  tasks:
    - name: update apt packages
      apt:
        upgrade: yes
        update_cache: yes
    - name: check if reboot is required
      become: true
      stat:
        path: /var/run/reboot-required
      register: reboot_required

    - name: notify Google Chat if reboot required
      when: reboot_required.stat.exists
      uri:
        url: '{{ google_chat_webhook }}'
        method: POST
        body: '{"text": "Reboot required on {{ inventory_hostname }}"}'
        body_format: json
        status_code: 200
