---
# Ansible playbook to run shell script to archive YouTube playlists
- hosts: ytdlp
  serial: 1
  tasks:
      - name: update apt
        become: yes
        apt:
          update_cache: yes
          name: yt-dlp
          state: latest
      - name: download AND playlist with yt-dlp
        shell: |
          yt-dlp \
          -o "{{sermon_archive_path}}/%(playlist_title)s/%(upload_date)s - %(title)s/%(upload_date)s - %(title)s.%(ext)s.%(ext)s" \
          --download-archive "{{sermon_archive_path}}/archive.txt" \
          --write-info-json \
          --merge-output-format mp4 \
          --write-thumbnail \
          --write-auto-sub \
          --windows-filenames \
          --retries 100 \
          --file-access-retries 50 \
          --no-clean-info-json \
          --print after_video:"  - %(title)s" \
          "https://www.youtube.com/playlist?list=PLbQ39sgTWJxeVK3iDlN10wl_REBksOL6n"
        register: and_status
        ignore_errors: true

      - name: download SW playlist with yt-dlp
        shell: |
          yt-dlp \
          -o "{{sermon_archive_path}}/%(playlist_title)s/%(upload_date)s - %(title)s/%(upload_date)s - %(title)s.%(ext)s.%(ext)s" \
          --download-archive "{{sermon_archive_path}}/archive.txt" \
          --write-info-json \
          --merge-output-format mp4 \
          --write-thumbnail \
          --write-auto-sub \
          --windows-filenames \
          --retries 100 \
          --file-access-retries 50 \
          --no-clean-info-json \
          --print after_video:"  - %(title)s" \
          "https://www.youtube.com/playlist?list=PLbQ39sgTWJxdLdfeabiqL4aMmj1qmZQhv"
        register: sw_status
        ignore_errors: true

      - name: download CRK playlist with yt-dlp
        shell: |
          yt-dlp \
          -o "{{sermon_archive_path}}/%(playlist_title)s/%(upload_date)s - %(title)s/%(upload_date)s - %(title)s.%(ext)s.%(ext)s" \
          --download-archive "{{sermon_archive_path}}/archive.txt" \
          --write-info-json \
          --merge-output-format mp4 \
          --write-thumbnail \
          --write-auto-sub \
          --windows-filenames \
          --retries 100 \
          --file-access-retries 50 \
          --no-clean-info-json \
          --print after_video:"  - %(title)s" \
          "https://www.youtube.com/playlist?list=PLbQ39sgTWJxedpjpydtd0R5TV2Wr-XQj3"
        register: crk_status
        ignore_errors: true

      - name: download MT playlist with yt-dlp
        shell: |
          yt-dlp \
          -o "{{sermon_archive_path}}/%(playlist_title)s/%(upload_date)s - %(title)s/%(upload_date)s - %(title)s.%(ext)s.%(ext)s" \
          --download-archive "{{sermon_archive_path}}/archive.txt" \
          --write-info-json \
          --merge-output-format mp4 \
          --write-thumbnail \
          --write-auto-sub \
          --windows-filenames \
          --retries 100 \
          --file-access-retries 50 \
          --no-clean-info-json \
          --print after_video:"  - %(title)s" \
          "https://www.youtube.com/playlist?list=PLbQ39sgTWJxcn2eaMMyS3w81u62JwYkTD"
        register: mt_status
        ignore_errors: true

      - name: send shell command status to google Chat
        uri:
          url: '{{ google_chat_webhook_yt }}'
          method: POST
          body: '{"cardsV2":[{"cardId":"ticket","card":{"header":{"title":"🤖 Y️outube Archive Bot","subtitle":"Run completed"},"sections":[{"header":"️🟡 AND 🟡 {{ "(Success!)" if and_status.rc == 0 else "(Status Code: " ~ and_status.rc ~ ")" }}","widgets":[{"textParagraph":{"text":"{{ and_status.stdout }}"}}]},{"header":"️🟢 SW 🟢 {{ "(Success!)" if sw_status.rc == 0 else "(Status Code: " ~ sw_status.rc ~ ")" }}","widgets":[{"textParagraph":{"text":"{{ sw_status.stdout }}"}}]},{"header":"️🔵 CRK 🔵 {{ "(Success!)" if crk_status.rc == 0 else "(Status Code: " ~ crk_status.rc ~ ")" }}","widgets":[{"textParagraph":{"text":"{{ crk_status.stdout }}"}}]},{"header":"️🔴 MT 🔴 {{ "(Success!)" if mt_status.rc == 0 else "(Status Code: " ~ mt_status.rc ~ ")" }}","widgets":[{"textParagraph":{"text":"{{ mt_status.stdout }}"}}]}]}}]}'
          body_format: json
          status_code: 200
        when: and_status.stdout != "" or sw_status.stdout != "" or crk_status.stdout != "" or mt_status.stdout != ""
